import { theme as antdTheme } from 'antd'

const sharedComponents = {
  Button: {
    primaryShadow: '0 4px 12px rgba(91, 47, 232, 0.3)',
    borderRadius: 10,
    controlHeight: 40,
    controlHeightLG: 48,
    fontWeight: 500,
  },
  Card: {
    borderRadiusLG: 16,
    paddingLG: 24,
  },
  Input: {
    controlHeight: 40,
    borderRadius: 10,
  },
  Modal: {
    borderRadiusLG: 20,
    titleFontSize: 18,
  },
  Tag: {
    borderRadiusSM: 8,
  },
}

export const lightTheme = {
  token: {
    colorPrimary: '#5B2FE8',
    colorSuccess: '#22C55E',
    colorWarning: '#F59E0B',
    colorError: '#EF4444',
    colorInfo: '#6366F1',
    colorBgBase: '#F5F3FF',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgLayout: '#F0EDFC',
    colorText: '#1A1145',
    colorTextSecondary: '#6B6580',
    colorBorder: '#E5E0F0',
    colorBorderSecondary: '#F0EDFC',
    borderRadius: 10,
    borderRadiusLG: 16,
    borderRadiusSM: 6,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontSize: 14,
    fontSizeHeading1: 32,
    fontSizeHeading2: 26,
    fontSizeHeading3: 20,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    boxShadow: '0 4px 12px rgba(91, 47, 232, 0.08)',
    boxShadowSecondary: '0 8px 32px rgba(91, 47, 232, 0.12)',
    colorLink: '#5B2FE8',
    colorLinkHover: '#7B4FF0',
    colorLinkActive: '#4A25C0',
  },
  components: {
    ...sharedComponents,
    Menu: {
      darkItemBg: '#151025',
      darkSubMenuItemBg: '#0D0A1A',
      darkItemSelectedBg: 'rgba(91, 47, 232, 0.3)',
      itemBorderRadius: 10,
      itemMarginInline: 8,
      itemHeight: 44,
      iconSize: 18,
    },
    Table: {
      borderRadiusLG: 16,
      headerBg: '#F0EDFC',
      headerColor: '#1A1145',
      rowHoverBg: '#F5F3FF',
    },
    Tabs: {
      inkBarColor: '#5B2FE8',
      itemActiveColor: '#5B2FE8',
      itemSelectedColor: '#5B2FE8',
    },
    Descriptions: {
      labelColor: '#6B6580',
    },
    Form: {
      labelColor: '#1A1145',
      labelFontSize: 14,
    },
  },
}

export const darkTheme = {
  algorithm: antdTheme.darkAlgorithm,
  token: {
    colorPrimary: '#8B6FFF',
    colorSuccess: '#22C55E',
    colorWarning: '#F59E0B',
    colorError: '#EF4444',
    colorInfo: '#6366F1',
    colorBgBase: '#0D0A1A',
    colorBgContainer: '#151025',
    colorBgElevated: '#1C1530',
    colorBgLayout: '#0D0A1A',
    colorText: '#F0EDFC',
    colorTextSecondary: '#A8A0C0',
    colorBorder: '#2A2240',
    colorBorderSecondary: '#1E1640',
    borderRadius: 10,
    borderRadiusLG: 16,
    borderRadiusSM: 6,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'PingFang SC', 'Microsoft YaHei', sans-serif",
    fontSize: 14,
    fontSizeHeading1: 32,
    fontSizeHeading2: 26,
    fontSizeHeading3: 20,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.4)',
    boxShadowSecondary: '0 8px 32px rgba(0, 0, 0, 0.5)',
    colorLink: '#8B6FFF',
    colorLinkHover: '#A78BFF',
    colorLinkActive: '#7B5FEE',
  },
  components: {
    ...sharedComponents,
    Menu: {
      darkItemBg: '#151025',
      darkSubMenuItemBg: '#0D0A1A',
      darkItemSelectedBg: 'rgba(139, 111, 255, 0.25)',
      itemBorderRadius: 10,
      itemMarginInline: 8,
      itemHeight: 44,
      iconSize: 18,
    },
    Table: {
      borderRadiusLG: 16,
      headerBg: '#1C1530',
      rowHoverBg: '#1E1640',
    },
    Tabs: {
      inkBarColor: '#8B6FFF',
      itemActiveColor: '#8B6FFF',
      itemSelectedColor: '#8B6FFF',
    },
    Descriptions: {
      labelColor: '#A8A0C0',
    },
    Form: {
      labelColor: '#F0EDFC',
      labelFontSize: 14,
    },
  },
}
